In [142]:
import pandas as pd
import re

In [209]:
vcf = pd.read_csv('target_cohort.csv')
vcf.head()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3553: DtypeWarning: Columns (1,5) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1323,Unnamed: 1324,Unnamed: 1325,Unnamed: 1326,Unnamed: 1327,Unnamed: 1328,Unnamed: 1329,Unnamed: 1330,Unnamed: 1331,##bcftools_viewCommand=view -Ov sabe_target_cohort.vcf.gz; Date=Tue Apr 4 18:10:49 2023
0,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,Sample_01,...,Sample_1315,Sample_1316,Sample_1317,Sample_1318,Sample_1319,Sample_1320,Sample_1321,Sample_1322,Sample_1323,Sample_1324
1,chr1,959139,.,G,A,2371.54,PASS,AC=37;AF=0.014;AN=2648;DP=42588;FS=1.75;MQ=250...,GT:AD:AF:DP:F1R2:F2R1:FT:GP:GQ:MIN_DP:PL:PS:SQ,"0/1:13,16:0.552:29:5,11:8,5:PASS:50,6.9634e-05...",...,"0/0:43,0:0:29:.:.:PASS:.:81:.:0,81,1215:.:.","0/0:26,0:0:23:.:.:PASS:.:66:.:0,66,990:.:.","0/0:39,1:0.025:40:.:.:PASS:.:73:.:0,73,1646:.:.","0/0:20,0:0:16:.:.:PASS:.:40:.:0,40,630:.:.","0/0:39,0:0:36:.:.:PASS:.:86:.:0,86,1315:.:.","0/0:31,1:0.031:32:.:.:PASS:.:64:.:0,64,1271:.:.","0/0:27,0:0:25:.:.:PASS:.:65:.:0,65,1035:.:.","0/0:29,1:0.033:29:.:.:PASS:.:71:.:0,71,1070:.:.","0/0:42,0:0:33:.:.:PASS:.:80:.:0,80,1368:.:.","0/0:32,0:0:31:.:.:PASS:.:82:.:0,82,1241:.:."
2,chr1,1127258,.,C,A,125752,PASS,AC=1454;AF=0.549;AN=2648;DP=47466;FS=0;MQ=248....,GT:AD:AF:DP:F1R2:F2R1:FT:GP:GQ:MIN_DP:PL:PS:SQ,"0/1:17,15:0.469:32:11,8:6,7:PASS:49.671,6.8598...",...,"0/1:11,11:0.5:22:5,10:6,1:PASS:50,6.5233e-05,5...","0/0:29,0:0:29:.:.:PASS:.:84:.:0,84,1260:.:.","0/1:18,17:0.486:35:7,7:11,10:PASS:49.938,6.575...","1/1:0,34:1:34:0,12:0,22:PASS:149.34,99.337,0:9...","0/1:26,23:0.469:49:16,9:10,14:PASS:49.595,6.93...","1/1:0,41:1:41:0,25:0,16:PASS:170.4,120.4,0:120...","0/1:14,12:0.462:26:7,6:7,6:PASS:49.665,6.8598e...","0/1:18,24:0.571:42:10,12:8,12:PASS:50,8.0247e-...","1/1:0,48:1:48:0,23:0,25:PASS:190.55,140.55,0:1...","0/1:22,17:0.436:39:9,7:13,10:PASS:48.476,8.335..."
3,chr1,1748780,.,G,A,104845,PASS,AC=1258;AF=0.476;AN=2644;DP=46266;FS=0.516;MQ=...,GT:AD:AF:DP:F1R2:F2R1:FT:GP:GQ:MIN_DP:PL:PS:SQ,"0/0:38,0:0:32:.:.:PASS:.:81:.:0,81,1347:.:.",...,"0/0:27,0:0:26:.:.:PASS:.:63:.:0,63,1080:.:.","1/1:0,36:1:36:0,16:0,20:PASS:154.43,104.43,0:1...","0/0:30,0:0:29:.:.:PASS:.:81:.:0,81,1215:.:.","0/1:18,10:0.357:28:11,5:7,5:PASS:44.968,0.0001...","0/0:32,1:0.03:30:.:.:PASS:.:81:.:0,81,1215:.:.","0/0:24,0:0:23:.:.:PASS:.:61:.:0,61,945:.:.","0/1:11,14:0.56:25:6,7:5,7:PASS:50,6.9375e-05,5...","0/1:17,12:0.414:29:12,6:5,6:PASS:48.122,8.879e...","0/0:41,0:0:32:.:.:PASS:.:84:.:0,84,1305:.:.","0/1:13,13:0.5:26:9,5:4,8:PASS:50,6.5233e-05,53..."
4,chr1,2115499,.,G,T,150576,PASS,AC=1718;AF=0.649;AN=2648;DP=47693;FS=0;MQ=250;...,GT:AD:AF:DP:F1R2:F2R1:FT:GP:GQ:MIN_DP:PL:PS:SQ,"0/1:17,15:0.469:32:11,11:6,4:PASS:49.73,6.8081...",...,"0/1:21,19:0.475:40:12,11:9,8:PASS:49.825,6.704...","1/1:1,37:0.974:38:0,13:1,24:PASS:150.92,100.92...","0/1:11,22:0.667:33:6,14:5,8:PASS:50,0.00017758...","0/1:11,14:0.56:25:5,6:6,8:PASS:50,6.9634e-05,5...","0/1:21,15:0.417:36:13,6:8,9:PASS:47.648,9.6297...","0/1:12,21:0.636:33:6,9:6,12:PASS:50,0.00013694...","1/1:0,23:1:23:0,12:0,11:PASS:116.23,66.229,1.0...","1/1:0,40:1:40:0,18:0,22:PASS:166.93,116.93,0:1...","0/1:17,27:0.614:44:10,20:7,7:PASS:50,0.0001998...","0/1:16,18:0.529:34:9,12:7,6:PASS:50,6.6527e-05..."

In [210]:
pgs = pd.read_csv('PGS002296_hmPOS_GRCh38.tsv', sep='\t')
pgs.head()

,rsID,chr,pos_hg19,pos_hg38,effect_allele,other_allele,effect_weight
0,rs115438739,chr1,894519,959139,G,A,0.050
1,rs9442373,chr1,1062638,1127258,C,A,-0.016
2,rs1014988,chr1,1680219,1748780,G,A,0.021
3,rs3128339,chr1,2046938,2115499,G,T,-0.019
4,rs4486390,chr1,2931440,3014876,C,T,0.024

In [216]:
# Set the column names to the values in the second row
vcf.columns = vcf.iloc[0]
# # Drop the second row and reset the index if needed
vcf = vcf.drop(0).reset_index(drop=True)

In [217]:
sample_columns = [x for x in vcf.columns if x.startswith('Sample')]

In [218]:
gen_dict = {'0/0': 0, '0/1': 1, '1/1' : 2, '0|0': 0, '0|1': 1, '1|1' : 2}

In [221]:
for col in sample_columns:
    person_id = re.findall('\d+$', col)[0]
    vcf['Person_'+str(person_id)] = vcf['Sample_'+str(person_id)] .apply(lambda x: gen_dict.get(x[:3], x))

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  This is separate from the ipykernel package so we can avoid doing imports until

In [222]:
vcf = vcf.rename(columns={'#CHROM': 'chr',  'POS': 'pos_hg38'})

In [223]:
cols = [x for x in vcf.columns if x.startswith('Person') ]
cols.append('chr')
cols.append('pos_hg38')
table = vcf[cols]

In [224]:
table['pos_hg38'] =  table['pos_hg38'].astype(int)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [225]:
table = pd.merge(pgs[['rsID', 'chr', 'pos_hg38']], table, how='right', on=['chr',  'pos_hg38'])
table = table.drop(columns=['chr', 'pos_hg38'])

In [226]:
table.head()

,rsID,Person_01,Person_02,Person_03,Person_04,Person_05,Person_06,Person_07,Person_08,Person_09,...,Person_1315,Person_1316,Person_1317,Person_1318,Person_1319,Person_1320,Person_1321,Person_1322,Person_1323,Person_1324
0,rs115438739,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,rs9442373,1,1,2,0,2,1,1,0,2,...,1,0,1,2,1,2,1,1,2,1
2,rs1014988,0,0,0,0,1,0,2,0,0,...,0,2,0,1,0,0,1,1,0,1
3,rs3128339,1,1,1,2,1,1,0,1,2,...,1,2,1,1,1,1,2,2,1,1
4,rs4486390,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [227]:
table = table.set_index('rsID').transpose()

In [228]:
table = table.reset_index()

In [229]:
table['s'] = table['index'].replace('^Person', 'Sample', regex=True)

In [230]:
table = table.drop(columns='index')
table.head()

rsID,rs115438739,rs9442373,rs1014988,rs3128339,rs4486390,rs76611986,rs2065524,rs2493292,rs7511635,rs3138159,...,rs138413,rs136829,rs4822211,rs137739,rs6009560,rs73183332,rs28573806,rs73188943,rs9616900,s
0,1,1,0,1,0,0,1,0,0,0,...,0,0,2,2,2,1,1,1,0,Sample_01
1,0,1,0,1,0,0,0,0,0,0,...,1,0,0,1,0,0,1,1,2,Sample_02
2,0,2,0,1,1,0,0,0,0,0,...,0,0,2,1,1,0,1,1,1,Sample_03
3,1,0,0,2,0,1,0,0,1,0,...,0,1,2,0,2,0,1,1,1,Sample_04
4,0,2,1,1,1,0,0,0,0,0,...,0,0,1,0,1,0,0,1,2,Sample_05

In [231]:
pheno = pd.read_csv('pheno.tsv', sep='\t')

In [232]:
df = pd.merge(table, pheno[['s', 'target_phenotype']], how='left', on='s').dropna()

In [233]:
df['target_phenotype'] = df['target_phenotype'].astype(int)

In [234]:
df = df.drop(columns='s')

In [235]:
df.head()

,rs115438739,rs9442373,rs1014988,rs3128339,rs4486390,rs76611986,rs2065524,rs2493292,rs7511635,rs3138159,...,rs138413,rs136829,rs4822211,rs137739,rs6009560,rs73183332,rs28573806,rs73188943,rs9616900,target_phenotype
1,0,1,0,1,0,0,0,0,0,0,...,1,0,0,1,0,0,1,1,2,1
2,0,2,0,1,1,0,0,0,0,0,...,0,0,2,1,1,0,1,1,1,1
3,1,0,0,2,0,1,0,0,1,0,...,0,1,2,0,2,0,1,1,1,1
4,0,2,1,1,1,0,0,0,0,0,...,0,0,1,0,1,0,0,1,2,1
9,0,2,1,1,0,0,0,1,1,0,...,1,0,1,1,1,0,0,1,2,1

In [236]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from skrebate import ReliefF

In [237]:
df.shape

(1092, 2166)

In [239]:
for col in

rs115438739         object
rs9442373           object
rs1014988           object
rs3128339           object
rs4486390           object
                     ...
rs73183332          object
rs28573806          object
rs73188943          object
rs9616900           object
target_phenotype     int64
Length: 2166, dtype: object

In [238]:
#example of 2 class problem
X = df.drop(columns='target_phenotype').values
y = df['target_phenotype'].values

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Create a ReliefF feature selection object
fs = ReliefF()

# Create a pipeline with the ReliefF feature selection object, a StandardScaler and a KNN classifier
pipeline = make_pipeline(fs, StandardScaler(), KNeighborsClassifier())

# Define the parameter grid for GridSearchCV
param_grid = {'relieff__n_neighbors': [5, 10, 15, 20]}

# Create a GridSearchCV object with 5-fold cross-validation
grid = GridSearchCV(pipeline, param_grid, cv=5)

# Fit the GridSearchCV object to the training data
grid.fit(X_train, y_train)

# Print the best parameters and the best score
print(f"Best parameters: {grid.best_params_}")
print(f"Best score: {grid.best_score_}")

# Evaluate the best model on the testing data
accuracy = grid.score(X_test, y_test)
print(f"Accuracy: {accuracy}")
X_train = fs.fit_transform(data, target)
print(X_train)
print("--------------")
print("(No. of tuples, No. of Columns before ReliefF) : "+str(data.shape)+
      "\n(No. of tuples , No. of Columns after ReliefF) : "+str(X_train.shape))

/opt/conda/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

  FitFailedWarning)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [181]:
df.head()

,rs115438739,rs9442373,rs1014988,rs3128339,rs4486390,rs76611986,rs2065524,rs2493292,rs7511635,rs3138159,...,rs138413,rs136829,rs4822211,rs137739,rs6009560,rs73183332,rs28573806,rs73188943,rs9616900,target_phenotype
1,1,1,0,1,0,0,1,0,0,0,...,0,0,2,2,2,1,1,1,0,1
2,1,1,0,1,0,0,1,0,0,0,...,0,0,2,2,2,1,1,1,0,1
3,1,1,0,1,0,0,1,0,0,0,...,0,0,2,2,2,1,1,1,0,1
4,1,1,0,1,0,0,1,0,0,0,...,0,0,2,2,2,1,1,1,0,1
9,1,1,0,1,0,0,1,0,0,0,...,0,0,2,2,2,1,1,1,0,1

In [176]:
df.to_csv('geno.csv', index=False)